package zhitong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagDeviceStatus extends Structure {
	/**
	 * \u8bbe\u5907\u53e5\u67c4<br>
	 * C type : PDEVICEHANDLE
	 */
	public Pointer pHandle;
	/**
	 * \u8bbe\u5907IP<br>
	 * C type : unsigned char[16]
	 */
	public byte[] ucDeviceIP = new byte[16];
	/**
	 * @see DEVICE_STATUS<br>
	 * \u8bbe\u5907\u72b6\u6001<br>
	 * C type : DEVICE_STATUS
	 */
	public int status;
	public tagDeviceStatus() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("pHandle", "ucDeviceIP", "status");
	}
	/**
	 * @param pHandle \u8bbe\u5907\u53e5\u67c4<br>
	 * C type : PDEVICEHANDLE<br>
	 * @param ucDeviceIP \u8bbe\u5907IP<br>
	 * C type : unsigned char[16]<br>
	 * @param status @see DEVICE_STATUS<br>
	 * \u8bbe\u5907\u72b6\u6001<br>
	 * C type : DEVICE_STATUS
	 */
	public tagDeviceStatus(Pointer pHandle, byte ucDeviceIP[], int status) {
		super();
		this.pHandle = pHandle;
		if ((ucDeviceIP.length != this.ucDeviceIP.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ucDeviceIP = ucDeviceIP;
		this.status = status;
	}
	public tagDeviceStatus(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagDeviceStatus implements Structure.ByReference {
		
	};
	public static class ByValue extends tagDeviceStatus implements Structure.ByValue {
		
	};
}
