package zhitong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagVersionInfo extends Structure {
	/**
	 * \u4e3b\u7248\u672c<br>
	 * C type : unsigned char[255]
	 */
	public byte[] ucMainVer = new byte[255];
	/**
	 * \u6b21\u7248\u672c<br>
	 * C type : unsigned char[255]
	 */
	public byte[] ucDSPVer = new byte[255];
	/**
	 * MCU\u7248\u672c<br>
	 * C type : unsigned char[255]
	 */
	public byte[] ucMCUVer = new byte[255];
	/**
	 * \u8bc6\u522b\u7b97\u6cd5\u7248\u672c<br>
	 * C type : unsigned char[255]
	 */
	public byte[] ucOCRVer = new byte[255];
	/**
	 * EEPROM\u7248\u672c\u53f7<br>
	 * C type : unsigned char[255]
	 */
	public byte[] ucEPROMVer = new byte[255];
	public tagVersionInfo() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ucMainVer", "ucDSPVer", "ucMCUVer", "ucOCRVer", "ucEPROMVer");
	}
	/**
	 * @param ucMainVer \u4e3b\u7248\u672c<br>
	 * C type : unsigned char[255]<br>
	 * @param ucDSPVer \u6b21\u7248\u672c<br>
	 * C type : unsigned char[255]<br>
	 * @param ucMCUVer MCU\u7248\u672c<br>
	 * C type : unsigned char[255]<br>
	 * @param ucOCRVer \u8bc6\u522b\u7b97\u6cd5\u7248\u672c<br>
	 * C type : unsigned char[255]<br>
	 * @param ucEPROMVer EEPROM\u7248\u672c\u53f7<br>
	 * C type : unsigned char[255]
	 */
	public tagVersionInfo(byte ucMainVer[], byte ucDSPVer[], byte ucMCUVer[], byte ucOCRVer[], byte ucEPROMVer[]) {
		super();
		if ((ucMainVer.length != this.ucMainVer.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ucMainVer = ucMainVer;
		if ((ucDSPVer.length != this.ucDSPVer.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ucDSPVer = ucDSPVer;
		if ((ucMCUVer.length != this.ucMCUVer.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ucMCUVer = ucMCUVer;
		if ((ucOCRVer.length != this.ucOCRVer.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ucOCRVer = ucOCRVer;
		if ((ucEPROMVer.length != this.ucEPROMVer.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.ucEPROMVer = ucEPROMVer;
	}
	public tagVersionInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagVersionInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends tagVersionInfo implements Structure.ByValue {
		
	};
}
