package zhitong;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
/**
 * JNA Wrapper for library <b>zhitong</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface ZhitongLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "zhitong";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(ZhitongLibrary.JNA_LIBRARY_NAME);
	public static final ZhitongLibrary INSTANCE = (ZhitongLibrary)Native.loadLibrary(ZhitongLibrary.JNA_LIBRARY_NAME, ZhitongLibrary.class);
	/** enum values */
	public static interface FEEKBACK_TYPE {
		/**
		 * \u6267\u884c\u6210\u529f<br>
		 * <i>native declaration : line 30</i>
		 */
		public static final int RESULT_OK = 0;
		/**
		 * \u5df2\u7ecf\u521d\u59cb\u5316<br>
		 * <i>native declaration : line 31</i>
		 */
		public static final int INIT_SUCCESS = 1;
		/**
		 * \u672a\u521d\u59cb\u5316<br>
		 * <i>native declaration : line 32</i>
		 */
		public static final int NO_INIT = 2;
		/**
		 * \u53c2\u6570\u4e0d\u6b63\u786e<br>
		 * <i>native declaration : line 33</i>
		 */
		public static final int PARAMS_ERROR = 3;
		/**
		 * SOCKET\u53e5\u67c4\u4e3aNULL<br>
		 * <i>native declaration : line 34</i>
		 */
		public static final int SOCKET_NULL = 4;
		/**
		 * \u7ebf\u7a0b\u5931\u8d25<br>
		 * <i>native declaration : line 35</i>
		 */
		public static final int THREAD_FAIL = 5;
		/**
		 * \u751f\u6210\u547d\u4ee4\u5931\u8d25<br>
		 * <i>native declaration : line 36</i>
		 */
		public static final int CREATE_FAIL = 6;
		/**
		 * \u53d1\u9001\u547d\u4ee4\u5931\u8d25<br>
		 * <i>native declaration : line 37</i>
		 */
		public static final int SEND_FAIL = 7;
		/**
		 * \u6ca1\u6709\u53d1\u73b0\u8bbe\u5907<br>
		 * <i>native declaration : line 38</i>
		 */
		public static final int NO_FIND_DEVICE = 8;
		/**
		 * \u8bbe\u5907\u5df2\u7ecf\u6253\u5f00<br>
		 * <i>native declaration : line 39</i>
		 */
		public static final int DEVICE_OPENED = 9;
		/**
		 * \u548c\u8bbe\u5907\u7684\u8fde\u63a5\u65ad\u5f00<br>
		 * <i>native declaration : line 40</i>
		 */
		public static final int DEVICE_DISCONNECT = 10;
		/**
		 * \u63a7\u5236\u7aef\u53e3\u672a\u8fde\u63a5<br>
		 * <i>native declaration : line 41</i>
		 */
		public static final int CONTORL_NOCONNECTION = 11;
		/**
		 * \u963b\u585e\u89e6\u53d1\u6ca1\u6709\u6536\u5230\u6570\u636e<br>
		 * <i>native declaration : line 42</i>
		 */
		public static final int NO_RECEIVED_DATA = 12;
		/**
		 * \u5176\u4ed6\u9519\u8bef<br>
		 * <i>native declaration : line 43</i>
		 */
		public static final int OTHER_ERROR = 100;
		/**
		 * \u51fd\u6570\u6267\u884c\u8d85\u65f6<br>
		 * <i>native declaration : line 44</i>
		 */
		public static final int TIME_OUT = 209;
	};
	/** enum values */
	public static interface DEVICE_STATUS {
		/**
		 * \u8fde\u63a5\u6210\u529f<br>
		 * <i>native declaration : line 50</i>
		 */
		public static final int CONNECT_SUCCESS = 0;
		/**
		 * \u751f\u6210\u53e5\u67c4\u9519\u8bef<br>
		 * <i>native declaration : line 51</i>
		 */
		public static final int CREATE_ERROR = 1;
		/**
		 * \u8fde\u63a5\u9519\u8bef<br>
		 * <i>native declaration : line 52</i>
		 */
		public static final int CONNECT_ERROR = 2;
		/**
		 * \u7f51\u7edc\u5f02\u5e38\u9519\u8bef<br>
		 * <i>native declaration : line 53</i>
		 */
		public static final int ABNORMALNET_ERROR = 3;
		/**
		 * \u8bbe\u5907\u590d\u4f4d<br>
		 * <i>native declaration : line 54</i>
		 */
		public static final int DEVICE_RESET = 4;
	};
	/** enum values */
	public static interface PLATE_COLOR {
		/**
		 * \u672a\u77e5\u8f66\u724c\u989c\u8272<br>
		 * <i>native declaration : line 61</i>
		 */
		public static final int NON_PLATE = 0;
		/** <i>native declaration : line 62</i> */
		public static final int BLUE_COLOR = 1;
		/** <i>native declaration : line 63</i> */
		public static final int WHITE_COLOR = 2;
		/** <i>native declaration : line 64</i> */
		public static final int BLACK_COLOR = 3;
		/**
		 * \u9ec4\u8272<br>
		 * <i>native declaration : line 65</i>
		 */
		public static final int YELLOW_COLOR = 4;
	};
	/** enum values */
	public static interface DEVICE_TRIGGERMODE {
		/**
		 * \u672a\u77e5<br>
		 * <i>native declaration : line 70</i>
		 */
		public static final int UNKNOWN_TRIGGER_MODE = 0;
		/**
		 * \u89c6\u9891<br>
		 * <i>native declaration : line 71</i>
		 */
		public static final int VIDEO_TRIGGER_MODE = 1;
		/**
		 * \u7ebf\u5708<br>
		 * <i>native declaration : line 72</i>
		 */
		public static final int LINE_TRIGGER_MODE = 2;
		/**
		 * \u6a21\u62df<br>
		 * <i>native declaration : line 73</i>
		 */
		public static final int SOFT_TRIGGER_MODE = 3;
	};
	/** enum values */
	public static interface USER_TYPE {
		/**
		 * \u6b63\u5e38\u7528\u6237<br>
		 * <i>native declaration : line 77</i>
		 */
		public static final int NORMAL_USER = 0;
		/**
		 * \u672a\u6388\u6743\u7528\u6237<br>
		 * <i>native declaration : line 78</i>
		 */
		public static final int UNKNOWN_USER = 1;
	};
	/** enum values */
	public static interface SHUTTER_PARAMS {
		/**
		 * 1/50<br>
		 * <i>native declaration : line 85</i>
		 */
		public static final int SHUTTER_50 = 6;
		/** <i>native declaration : line 86</i> */
		public static final int SHUTTER_75 = 7;
		/** <i>native declaration : line 87</i> */
		public static final int SHUTTER_100 = 8;
		/** <i>native declaration : line 88</i> */
		public static final int SHUTTER_120 = 9;
		/** <i>native declaration : line 89</i> */
		public static final int SHUTTER_150 = 10;
		/** <i>native declaration : line 90</i> */
		public static final int SHUTTER_215 = 11;
		/** <i>native declaration : line 91</i> */
		public static final int SHUTTER_300 = 12;
		/** <i>native declaration : line 92</i> */
		public static final int SHUTTER_425 = 13;
		/** <i>native declaration : line 93</i> */
		public static final int SHUTTER_600 = 14;
		/** <i>native declaration : line 94</i> */
		public static final int SHUTTER_1000 = 15;
		/** <i>native declaration : line 95</i> */
		public static final int SHUTTER_1250 = 16;
		/** <i>native declaration : line 96</i> */
		public static final int SHUTTER_1750 = 17;
		/** <i>native declaration : line 97</i> */
		public static final int SHUTTER_2500 = 18;
		/** <i>native declaration : line 98</i> */
		public static final int SHUTTER_3500 = 19;
		/** <i>native declaration : line 99</i> */
		public static final int SHUTTER_6000 = 20;
		/**
		 * 1/10000<br>
		 * <i>native declaration : line 100</i>
		 */
		public static final int SHUTTER_10000 = 21;
	};
	/** enum values */
	public static interface MAIN_CMD {
		/**
		 * \u7cfb\u7edf\u6307\u4ee4<br>
		 * <i>native declaration : line 105</i>
		 */
		public static final int SYSTEM_CMD = 0x00;
		/**
		 * \u8c03\u5149\u6307\u4ee4<br>
		 * <i>native declaration : line 106</i>
		 */
		public static final int LIGHT_CMD = 0x20;
		/**
		 * \u53e0\u52a0\u6307\u4ee4<br>
		 * <i>native declaration : line 107</i>
		 */
		public static final int OSD_CMD = 0x30;
		/**
		 * \u5355\u7247\u673a\u6307\u4ee4<br>
		 * <i>native declaration : line 108</i>
		 */
		public static final int EPLD_CMD = 0x60;
		/**
		 * \u8865\u5149\u6307\u4ee4<br>
		 * <i>native declaration : line 109</i>
		 */
		public static final int LED_CMD = 0x70;
		/**
		 * \u76f8\u673a\u63a7\u5236\u6307\u4ee4<br>
		 * <i>native declaration : line 110</i>
		 */
		public static final int CAMERA_CMD = 0x71;
		/**
		 * \u52a8\u4f5c\u6307\u4ee4<br>
		 * <i>native declaration : line 111</i>
		 */
		public static final int MOVE_CMD = 0x80;
		/**
		 * \u6293\u62cd\u6570\u636e<br>
		 * <i>native declaration : line 112</i>
		 */
		public static final int CAPTURE_DATA = 0xFF;
	};
	/** enum values */
	public static interface SYSTEM_SUBCMD {
		/**
		 * \u5fc3\u8df3<br>
		 * <i>native declaration : line 117</i>
		 */
		public static final int HEART_CMD = 0x00;
		/**
		 * \u7248\u672c\u4fe1\u606f<br>
		 * <i>native declaration : line 118</i>
		 */
		public static final int VERSION_INFO = 0x04;
		/**
		 * \u56fe\u50cf\u538b\u7f29\u6bd4<br>
		 * <i>native declaration : line 119</i>
		 */
		public static final int IMAGE_QUALITY = 0x05;
		/**
		 * \u662f\u5426\u91cd\u542f<br>
		 * <i>native declaration : line 120</i>
		 */
		public static final int DEVICE_RESTART = 0x0C;
		/**
		 * \u91cd\u542f\u65f6\u95f4<br>
		 * <i>native declaration : line 121</i>
		 */
		public static final int RESTART_TIME = 0x0D;
		/**
		 * \u8bc6\u522b\u53c2\u6570<br>
		 * <i>native declaration : line 122</i>
		 */
		public static final int OCR_PARAMS = 0x16;
		/**
		 * \u8bbe\u5907\u5e8f\u5217\u53f7<br>
		 * <i>native declaration : line 123</i>
		 */
		public static final int SERIRAL_NO = 0x18;
		/**
		 * \u7b97\u6cd5\u53c2\u6570<br>
		 * <i>native declaration : line 124</i>
		 */
		public static final int ALG_PARAMS = 0x1A;
		/**
		 * \u8bbe\u5907\u7f16\u53f7<br>
		 * <i>native declaration : line 125</i>
		 */
		public static final int DEVICE_ID = 0x1B;
		/**
		 * \u673a\u5668\u7801<br>
		 * <i>native declaration : line 126</i>
		 */
		public static final int DEVICE_CODE = 0x1C;
		/**
		 * \u6388\u6743\u7801<br>
		 * <i>native declaration : line 127</i>
		 */
		public static final int AUTHOR_INFO = 0x1D;
		/**
		 * \u6388\u6743\u622a\u6b62\u65f6\u95f4<br>
		 * <i>native declaration : line 128</i>
		 */
		public static final int AUTHOR_VALIDTIME = 0x23;
		/**
		 * \u5de5\u4f5c\u6a21\u5f0f\uff0c0\u6b63\u5e38\uff0c1\u66dd\u5149\u6d4b\u8bd5\u6a21\u5f0f<br>
		 * <i>native declaration : line 129</i>
		 */
		public static final int WORK_MODE = 0x1E;
		/**
		 * \u6821\u65f6\u65b9\u5f0f0 SDK 1 NTP<br>
		 * <i>native declaration : line 130</i>
		 */
		public static final int VERIFYTIME_MODE = 0x1F;
		/**
		 * NTP\u670d\u52a1IP<br>
		 * <i>native declaration : line 131</i>
		 */
		public static final int NTP_SERVERIP = 0x20;
		/** <i>native declaration : line 132</i> */
		public static final int NTP_TIMEOUT = 0x21;
	};
	/** enum values */
	public static interface VERSION_OBJECT {
		/**
		 * \u4e3b\u7248\u672c<br>
		 * <i>native declaration : line 137</i>
		 */
		public static final int MAIN_VERSION = 0x00;
		/**
		 * \u6b21\u7248\u672c<br>
		 * <i>native declaration : line 138</i>
		 */
		public static final int DSP_SUBVERSION = 0x01;
		/**
		 * MCU\u7248\u672c<br>
		 * <i>native declaration : line 139</i>
		 */
		public static final int MCU_VERSION = 0x02;
		/**
		 * \u8bc6\u522b\u7b97\u6cd5\u7248\u672c<br>
		 * <i>native declaration : line 140</i>
		 */
		public static final int ALG_VERSION = 0x03;
		/**
		 * JPG\u7248\u672c\u4fe1\u606f<br>
		 * <i>native declaration : line 141</i>
		 */
		public static final int JPG_VERSION = 0x04;
		/**
		 * EEPROM\u7248\u672c\u53f7<br>
		 * <i>native declaration : line 142</i>
		 */
		public static final int EEPROM_VERSION = 0x05;
	};
	/** enum values */
	public static interface IMAGE_QUALITY_OBJECT {
		/**
		 * \u5927\u56fe<br>
		 * <i>native declaration : line 148</i>
		 */
		public static final int BIG_IMAGE_QUALITY = 0x00;
		/**
		 * CIF\u56fe<br>
		 * <i>native declaration : line 149</i>
		 */
		public static final int CIF_IMAGE_QUALITY = 0x01;
		/**
		 * \u8f66\u724c\u56fe<br>
		 * <i>native declaration : line 150</i>
		 */
		public static final int PLATE_IMAGE_QUALITY = 0x02;
	};
	/** enum values */
	public static interface LIGHT_SUBCMD {
		/**
		 * \u8c03\u5149\u6a21\u5f0f<br>
		 * <i>native declaration : line 156</i>
		 */
		public static final int LIGHT_MODE = 0x00;
		/**
		 * \u81ea\u52a8\u8c03\u5149\u4f7f\u80fd<br>
		 * <i>native declaration : line 157</i>
		 */
		public static final int AUTOLIGHT_ENABLE = 0x01;
		/**
		 * \u7cfb\u7edf\u65f6\u95f4<br>
		 * <i>native declaration : line 158</i>
		 */
		public static final int SYSTEM_TIME = 0x02;
		/**
		 * \u8c03\u5149\u53c2\u6570\u8868\uff0c\u5206\u56db\u5957<br>
		 * <i>native declaration : line 159</i>
		 */
		public static final int LIGHT_PARAMS = 0x03;
		/**
		 * \u56fe\u7247\u4eae\u5ea6<br>
		 * <i>native declaration : line 160</i>
		 */
		public static final int IMAGE_BRIGHTNESS = 0x07;
		/**
		 * \u76f8\u673a\u5f53\u524d\u72b6\u6001<br>
		 * <i>native declaration : line 161</i>
		 */
		public static final int CAMERA_CURSTATUS = 0x0A;
		/**
		 * \u6444\u50cf\u5934\u53c2\u6570<br>
		 * <i>native declaration : line 162</i>
		 */
		public static final int CAMERA_PARAMS = 0x0B;
		/**
		 * \u5f53\u524d\u8c03\u5149\u57fa\u51c6<br>
		 * <i>native declaration : line 163</i>
		 */
		public static final int CUR_LIGHTBASE = 0x0D;
		/**
		 * \u8c03\u5149\u6709\u6548\u6b21\u6570<br>
		 * <i>native declaration : line 164</i>
		 */
		public static final int LIGHT_VALIDNUM = 0x0E;
		/**
		 * \u767d\u5929\u66dd\u5149\u8865\u507f<br>
		 * <i>native declaration : line 165</i>
		 */
		public static final int DAY_EXPOSURE_COMPENSATION = 0x0F;
		/**
		 * \u591c\u95f4\u66dd\u5149\u8865\u507f<br>
		 * <i>native declaration : line 166</i>
		 */
		public static final int NIGHT_EXPOSURE_COMPENSATION = 0x10;
		/**
		 * \u53c2\u8003\u589e\u76ca<br>
		 * <i>native declaration : line 167</i>
		 */
		public static final int REF_GAIN = 0x11;
		/**
		 * \u53c2\u8003\u4eae\u5ea6<br>
		 * <i>native declaration : line 168</i>
		 */
		public static final int REF_BRIGHTNESS = 0x12;
	};
	/** enum values */
	public static interface LIGHT_MODE_VALUE {
		/**
		 * \u81ea\u52a8\u8c03\u5149<br>
		 * <i>native declaration : line 174</i>
		 */
		public static final int AUTO_LIGHT = 0x00;
		/**
		 * \u6df7\u5408\u8c03\u5149<br>
		 * <i>native declaration : line 175</i>
		 */
		public static final int MIXED_LIGHT = 0x01;
	};
	/** enum values */
	public static interface CAMERA_CURSTATUS_PARAMS {
		/**
		 * \u5feb\u95e8<br>
		 * <i>native declaration : line 181</i>
		 */
		public static final int SHUTTER_VALUE = 0x00;
		/**
		 * \u5149\u5708<br>
		 * <i>native declaration : line 182</i>
		 */
		public static final int APARTURE_VALUE = 0x01;
		/**
		 * \u589e\u76ca<br>
		 * <i>native declaration : line 183</i>
		 */
		public static final int GAIN_VALUE = 0x02;
		/**
		 * \u89c6\u91ce<br>
		 * <i>native declaration : line 184</i>
		 */
		public static final int VIEW_VALUE = 0x03;
		/**
		 * \u7126\u8ddd<br>
		 * <i>native declaration : line 185</i>
		 */
		public static final int F_VALUE = 0x04;
		/**
		 * \u8c03\u4eae<br>
		 * <i>native declaration : line 186</i>
		 */
		public static final int BRIGHT_NUM = 0x05;
		/**
		 * \u8c03\u6697<br>
		 * <i>native declaration : line 187</i>
		 */
		public static final int DARK_NUM = 0x06;
	};
	/** enum values */
	public static interface LED_SUBCMD {
		/**
		 * \u4f7f\u80fd<br>
		 * <i>native declaration : line 193</i>
		 */
		public static final int ENABLE_LED = 0x00;
		/**
		 * \u5f00\u5173\u706f\u57fa\u51c6<br>
		 * <i>native declaration : line 194</i>
		 */
		public static final int OPEN_CLOSE_BASE = 0x01;
		/**
		 * LED\u4eae\u5ea6<br>
		 * <i>native declaration : line 195</i>
		 */
		public static final int LED_BRIGHTNESS = 0x02;
		/**
		 * LED\u72b6\u6001<br>
		 * <i>native declaration : line 196</i>
		 */
		public static final int LED_STATUS = 0x03;
		/**
		 * LED\u5ef6\u8fdf<br>
		 * <i>native declaration : line 197</i>
		 */
		public static final int LED_DELAY = 0x04;
	};
	/** enum values */
	public static interface OSD_SUBCMD {
		/**
		 * \u4f7f\u80fd\u63a7\u5236<br>
		 * <i>native declaration : line 202</i>
		 */
		public static final int OSD_ENABLE = 0x0C;
		/**
		 * \u4fe1\u606f\u5185\u5bb9<br>
		 * <i>native declaration : line 203</i>
		 */
		public static final int OSD_INFO = 0x0D;
	};
	/** enum values */
	public static interface CAMERA_CONTROL_CMD {
		/**
		 * \u70b9\u66dd\u5149<br>
		 * <i>native declaration : line 209</i>
		 */
		public static final int POINT_EXPOSURE = 0x06;
		/**
		 * \u76f8\u673a\u76f8\u4f4d<br>
		 * <i>native declaration : line 210</i>
		 */
		public static final int CAMERA_PHASE = 0x07;
	};
	/** enum values */
	public static interface OSD_ENABLE_OBJECT {
		/**
		 * \u65f6\u95f4\u53e0\u52a0\u4f7f\u80fd<br>
		 * <i>native declaration : line 219</i>
		 */
		public static final int OSD_TIME_ENABLE = 0x00;
		/**
		 * \u81ea\u5b9a\u4e49\u4fe1\u606f\u53e0\u52a0\u4f7f\u80fd<br>
		 * <i>native declaration : line 220</i>
		 */
		public static final int OSD_INFO_ENABLE = 0x03;
		/**
		 * \u8bc6\u522b\u7ed3\u679c\u53e0\u52a0\u4f7f\u80fd<br>
		 * <i>native declaration : line 221</i>
		 */
		public static final int OSD_PLATE_ENABLE = 0x04;
	};
	/** enum values */
	public static interface EPLD_SUBCMD {
		/**
		 * \u7ebf\u5708\u89e6\u53d1\u6781\u6027<br>
		 * <i>native declaration : line 229</i>
		 */
		public static final int LINE_POLARITY = 0x01;
		/**
		 * \u76f8\u673a\u83dc\u5355<br>
		 * <i>native declaration : line 230</i>
		 */
		public static final int CAMERA_MENU = 0x0A;
		/**
		 * \u89c6\u91ce\u7126\u8ddd<br>
		 * <i>native declaration : line 231</i>
		 */
		public static final int VIEW_F = 0x0B;
	};
	/** enum values */
	public static interface VIEW_F_OBJECT {
		/**
		 * \u89c6\u91ce<br>
		 * <i>native declaration : line 238</i>
		 */
		public static final int VIEW_OBJECT = 0x00;
		/**
		 * \u7126\u8ddd<br>
		 * <i>native declaration : line 239</i>
		 */
		public static final int F_OBJECT = 0x01;
	};
	/** enum values */
	public static interface LED_STATUS_OBJECT {
		/**
		 * \u5f00\u706f\u57fa\u51c6<br>
		 * <i>native declaration : line 245</i>
		 */
		public static final int OPEN_BASE = 0x00;
		/**
		 * \u5173\u706f\u57fa\u51c6<br>
		 * <i>native declaration : line 246</i>
		 */
		public static final int CLOSE_BASE = 0x01;
	};
	/** enum values */
	public static interface WORKMODE {
		/**
		 * \u6b63\u5e38\u5de5\u4f5c\u6a21\u5f0f<br>
		 * <i>native declaration : line 253</i>
		 */
		public static final int NORMAL_WORKMODE = 0;
		/**
		 * \u89c6\u9891\u66dd\u5149\u6d4b\u8bd5\u6a21\u5f0f<br>
		 * <i>native declaration : line 254</i>
		 */
		public static final int VIDEO_EXPOSURE = 1;
	};
	/** enum values */
	public static interface MAINDIRECT {
		/**
		 * \u5de6\u4e0a\u884c\u9a76<br>
		 * <i>native declaration : line 362</i>
		 */
		public static final int LEFT_TOP = 0;
		/** <i>native declaration : line 363</i> */
		public static final int LEFT_BOTTOM = 1;
		/** <i>native declaration : line 364</i> */
		public static final int RIGHT_TOP = 2;
		/** <i>native declaration : line 365</i> */
		public static final int RIGHT_BOTTOM = 3;
		/**
		 * \u4e0d\u786e\u5b9a<br>
		 * <i>native declaration : line 366</i>
		 */
		public static final int UNDECIDED = 4;
	};
	/** enum values */
	public static interface TRIGGER_MODE {
		/**
		 * \u7ebf\u5708\u89e6\u53d1<br>
		 * <i>native declaration : line 372</i>
		 */
		public static final int LINE_TRIGGER = 0;
		/**
		 * \u89c6\u9891\u89e6\u53d1<br>
		 * <i>native declaration : line 373</i>
		 */
		public static final int VIDEO_TRIGGER = 2;
	};
	public static final int INVALID_HANLE = (int)0;
	public static final int IP_MAX_LEN = (int)16;
	public static final int MACADDR_LEN = (int)6;
	public static final int VERSION_LEN = (int)255;
	public static final int MAX_PLATE_LEN = (int)16;
	public static final int MAX_TIME_LEN = (int)8;
	public static final int AUTHORINFO_LEN = (int)100;
	public static final int SERIALNO_LEN = (int)20;
	public static final int FEEKMSG_MAX_LEN = (int)100;
	public static final int CMD_LEN = (int)512;
	public static final int CMD_READ = (int)0;
	public static final int CMD_WRITE = (int)1;
	public static final int ENABLE_FUNCTION = (int)1;
	public static final int DISABLE_FUNCTION = (int)0;
}
